CREATE TABLE IF NOT EXISTS support_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER,
    message VARCHAR(1000) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT ck_support_requests_message_length CHECK (char_length(trim(message)) BETWEEN 5 AND 1000)
);

CREATE INDEX IF NOT EXISTS idx_support_requests_read_created
    ON support_requests(is_read, created_at DESC);
