BEGIN;

CREATE TABLE IF NOT EXISTS seat_holds (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    showtime_id INTEGER NOT NULL,
    seat_id INTEGER NOT NULL,
    reservation_id INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (showtime_id) REFERENCES showtimes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (seat_id) REFERENCES seats(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uk_seat_holds_showtime_seat UNIQUE (showtime_id, seat_id),
    CONSTRAINT uk_seat_holds_reservation_seat UNIQUE (reservation_id, seat_id),
    CONSTRAINT ck_seat_holds_status CHECK (status IN ('HELD', 'BOOKED'))
);

CREATE INDEX IF NOT EXISTS idx_seat_holds_reservation
    ON seat_holds(reservation_id);

CREATE INDEX IF NOT EXISTS idx_seat_holds_active
    ON seat_holds(showtime_id, status, expires_at);

-- Do not silently hide historical double bookings during deployment.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM reservations r
        JOIN reservation_status status ON status.id = r.status_id
        JOIN reservation_seat ON reservation_seat.reservation_id = r.id
        WHERE status.name = 'PAID'
        GROUP BY r.showtime_id, reservation_seat.seat_id
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Cannot create seat_holds: duplicate paid seats exist for a showtime';
    END IF;
END $$;

-- Preserve existing paid bookings as permanent seat claims.
INSERT INTO seat_holds (
    showtime_id,
    seat_id,
    reservation_id,
    status,
    expires_at,
    created_at,
    updated_at
)
SELECT
    r.showtime_id,
    reservation_seat.seat_id,
    r.id,
    'BOOKED',
    r.end_time,
    r.start_time,
    CURRENT_TIMESTAMP
FROM reservations r
JOIN reservation_status status ON status.id = r.status_id
JOIN reservation_seat ON reservation_seat.reservation_id = r.id
WHERE status.name = 'PAID'
ON CONFLICT (showtime_id, seat_id) DO NOTHING;

-- Preserve pending reservations that have not expired yet.
INSERT INTO seat_holds (
    showtime_id,
    seat_id,
    reservation_id,
    status,
    expires_at,
    created_at,
    updated_at
)
SELECT
    r.showtime_id,
    reservation_seat.seat_id,
    r.id,
    'HELD',
    r.end_time,
    r.start_time,
    CURRENT_TIMESTAMP
FROM reservations r
JOIN reservation_status status ON status.id = r.status_id
JOIN reservation_seat ON reservation_seat.reservation_id = r.id
WHERE status.name = 'PENDING'
  AND r.end_time > CURRENT_TIMESTAMP
ON CONFLICT (showtime_id, seat_id) DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_tickets_reservation'
    ) THEN
        ALTER TABLE tickets
            ADD CONSTRAINT uk_tickets_reservation UNIQUE (reservation_id);
    END IF;
END $$;

ANALYZE seat_holds;

COMMIT;
